- name: Install Maven
  hosts: localhost
  strategy: free
  gather_facts: no
  tasks:
  - name: Create /opt directory
    file: path=/opt state=directory
  
  - name: Download Maven3
    get_url: dest=/opt/maven-3.8.5-bin.tar.gz url=http://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
    
  - name: Transfer Maven Installation File
    copy: src=./packages/apache-maven-3.8.5-bin.tar.gz dest=/opt mode=0777
        
  - name: Unpack Maven3
    action: command creates=/opt/maven chdir=/opt tar zxvf /opt/apache-maven-3.8.5-bin.tar.gz

  - name: Create Maven3 directory link
    file: path=/opt/maven src=/opt/apache-maven-3.8.5 state=link
  
  - name: Set mvn link
    action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1
    
  - name: Export Maven Path
    shell: export PATH=/opt/apache-maven-3.8.5/bin:$PATH
    
  - name: echo PATH
    shell: echo $PATH
    
  - name: Remove Maven3 archive
    file: path=/opt/apache-maven-3.8.5-bin.tar.gz state=absent
    
  - name: Clone a github repository
    git:
      repo: https://github.com/DidhitiKumar/Ansible_CI-CD.git
      dest: /var/lib/awx/projects/automation
      clone: yes
      update: yes
