--- 
- name: "Python Script run"
  become: true
  gather_facts: false
  hosts: localhost
  strategy: free
  tasks: 
    - name: Run the HelloWorld File
      shell: python3 HelloWorld.py
      register : command_output
      
    - name: Print the script output  
      ansible.builtin.debug:
            var: command_output.stdout_lines
