---
- name: Using ServiceNow Collection
  become: true
  gather_facts: no
  hosts: localhost
  strategy: free
  collections:
    - servicenow.servicenow
  vars:
    - username: admin
    - password: qDI!k+R49fNa
    - keyword: Active

  tasks:
    - name: Search for incident assigned by description, return specific fields
      servicenow.servicenow.snow_record_find:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: dev119990
        table: incident
        query:
          AND:
            equals:
              active: "True"
              state: "1"
            contains:
              short_description: "{{ keyword }}"
        return_fields:
          - sys_id
          - number
          - opened_at
          - short_description
          - state
      register: incidents
    - name: print result
      debug:
        msg: "incident: {{ incidents.record }}"
      notify:
        - SM1_slack
        - SM2_slack
  handlers:
  - name: SM1_slack
    slack:
      domain: bluebuddytesting.slack.com
      token: "T03N99ZN6A2/B040JEPPQCU/kibahLh6tWjVxCUu11Qycl5X"
      msg: To invoke runbook please use utterances like the ones below-
           1. Work Processes 
      channel: "#random"
      when: short_description == "Work Processes"
  - name: SM2_slack
    slack:
      domain: bluebuddytesting.slack.com
      token: "T03N99ZN6A2/B040JEPPQCU/kibahLh6tWjVxCUu11Qycl5X"
      msg: To invoke runbook please use utterances like the ones below-
           1. Show online users AL08
           2. active users
           3. list online users
      channel: "#random"
      when: short_description == "active users"
