- name: notify
  become: true
  gather_facts: no
  hosts: localhost
  strategy: free
  tasks:
  - name: Run a python script
    shell: python3 HelloWorld.py
    notify: Python_notification_slack
  handlers:
  - name: Python_notification_slack
    slack:
      domain: bluebuddytesting.slack.com
      token: "T03N99ZN6A2/B040JEPPQCU/kibahLh6tWjVxCUu11Qycl5X"
      msg: httpd installed
      channel: "#random"
